CREATE DATABASE VF_DATAMART;

CREATE TABLE ENTITY_TRANSACTION_MASTER 
(

	ENTITY_NAME  VARCHAR(30), 
	ENTITY_CATEGORY  VARCHAR(50), 
	ENTITY_TYPE  VARCHAR(50), 
	ENTITY_SUB_TYPE  VARCHAR(50), 
	ENTITY_VALUE  VARCHAR(100), 
	TXN_DATE TIMESTAMP, 
	ATTR_NAME1 VARCHAR(50), 
	ATTR_VALUE1 VARCHAR(50), 
	ATTR_NAME2 VARCHAR(50), 
	ATTR_VALUE2 VARCHAR(50), 
	ATTR_NAME3 VARCHAR(50), 
	ATTR_VALUE3 VARCHAR(50)
);